# HOW TO: https://jellis18.github.io/post/2017-11-20-automating-jupyter-slides/


language: python
cache: pip

python:
    - "3.6"

# install jupyter and get reveal.js as we will need it to build the website
# from Travis
install:
    - pip install jupyter
    - cd MachineLearning/Slides
    - wget https://github.com/hakimel/reveal.js/archive/master.zip
    - unzip master.zip
    - mv reveal.js-master reveal.js

script:
    - jupyter nbconvert Girls\ Can\ Do\ Machine\ Learning.ipynb --to slides --reveal-prefix=reveal.js

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
      git checkout --orphan gh-pages
      ## git rm -rf --cached .  ## This removes all files, too many
      cp Girls\ Can\ Do\ Machine\ Learning.slides.html index.html
      git add -f --ignore-errors *.html files reveal.js
      git -c user.name='Travis' -c user.email='Travis' commit -am init
      git push --force --quiet https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi


after_deploy:
    - "echo 'deployed!'"
