# HOW TO: https://jellis18.github.io/post/2017-11-20-automating-jupyter-slides/


language: python
cache: pip

python:
    - "2.7"

# install jupyter and get reveal.js as we will need it to build the website
# from Travis
install:
    - pip install jupyter
    - cd demo_Jupyter-to-Slides/xarray_intro_acinn    
    - wget https://github.com/hakimel/reveal.js/archive/master.zip
    - unzip master.zip
    - mv reveal.js-master reveal.js

script:
    - jupyter nbconvert ACINN_workshop_xarray-slides.ipynb --to slides --reveal-prefix=reveal.js

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    git checkout --orphan gh-pages
    git rm -rf --cached .
    cd demo_Jupyter-to-Slides/xarray_intro_acinn
    mv ACINN_workshop_xarray-slides.slides.html index.html
    git add -f --ignore-errors index.html figures img reveal.js
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi

